# Generated by Django 5.0.4 on 2024-05-17 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('apellidoPat', models.TextField()),
                ('apellidoMat', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('apellidoPat', models.TextField()),
                ('apellidoMat', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cal', models.FloatField()),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.alumno')),
                ('id_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.materia')),
                ('id_profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profesor')),
            ],
        ),
    ]
